name: "My manual workflow"

on: 
    workflow_dispatch:

jobs:
    say-hello-world:
        runs-on: ubuntu-24.04
        steps:
            - name: "Hello World"
              run: echo "Hello World"